[package]
name = "lambda-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.51"
lambda_http = "0.7"
lambda_runtime = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros"] }
