service: lambda-proxy
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  memorySize: 128
  architecture: arm64

plugins:
  - serverless-rust-plugin

custom:
  rust:
    cargoLambda:
      docker: false
    api:
      port: 9000

functions:
  hello:
    name: hello
    handler: lambda-proxy
    events:
      - http:
          path: hello
          method: get
          request:
            parameters:
              querystrings:
                firstName: true
    rust:
      port: 8888
